name: Install azure-cli
description: |-
  Installs the latest version of azure-cli. 
  This is helpful when running on a self-hosted server, or you try the ci/cd pipeline locally using act.
runs:
  using: composite
  steps:
    - name: install azure-cli
      env:
        installer_script_path: ${{ github.action_path }}/install_cli.sh
      run: |
        chmod +x $installer_script_path
        bash $installer_script_path
      shell: bash
